twitter-to-kafka-service:
  twitter-keywords:
    - Bangalore
  welcome-message: Hello Microservices!

retry-config:
  initial-interval-ms: 1000
  max-interval-ms: 10000
  multiplier: 2.0
  maxAttempts: 3
  sleep-time-ms: 2000

kafka-config:
  bootstrap-server: 127.0.0.1:9092
  schema-registry-url-key: schema.registry.url
  schema-registry-url: localhost:8081
  topic-name: twitter-topic
  topic-names-to-create:
    - twitter-topic
  num-of-partitions: 3
  replication-factor: 1

kafka-producer-config:
  key-serializer-class: org.apache.kafka.common.serialization.StringSerializer
  value-serializer-class: org.springframework.kafka.support.serializer.JsonSerializer
  compression-type: snappy
  acks: all
  #
  batch-size: 16384
  # tune for higher throughtput
  batch-size-boost-factor: 100
  # add a delay on producer in case of light load
  linger-ms: 5
  # after 60 seconds if no acknowledgement comes producer will throw time out error
  request-timeout-ms: 60000
  # it will retry 5 times in case of error
  retry-count: 5

